#!/usr/bin/env python3
"""Split a legacy single-file tracker.config into the v2.1 layered configs.

Usage:
    python3 tools/split_config.py path/to/tracker.config

Writes site.config and environment.config next to the input file (refuses to
overwrite existing ones). The legacy file is left untouched; v2.1 ignores it
once site.config exists. Only values that differ from the application defaults
matter, but this tool copies every key faithfully — trimming is optional and
can be done later by deleting lines.

Key routing (PROPOSAL_V2.1.md §2a):
  site.config        — fleet identity: buoys, homes, alert policy, map view
  environment.config — infrastructure: broker, ports, smtp transport, logging
Unknown sections/keys go to environment.config (safe default) with a notice.
"""

import configparser
import sys
from pathlib import Path

# section -> 'site' | 'env' | dict of key -> 'site'/'env' (split section)
ROUTING = {
    'app': 'site',
    'special_nodes': 'site',
    'special_nodes_settings': 'site',
    'battery': 'site',
    'app_features': 'site',
    'mqtt': 'env',
    'debug': 'env',
    'database': 'env',
    'security': 'env',
    'webapp': {
        'default_center': 'site',
        'default_zoom': 'site',
        'status_blue_threshold': 'site',
        'status_orange_threshold': 'site',
        # everything else (host, port, api_polling_interval, ...) -> env
    },
    'alerts': {
        'enabled': 'site',
        'alert_cooldown': 'site',
        # smtp_*, email_from, tracker_url -> env
    },
}

DROPPED_KEYS = {
    ('app', 'version'),          # version lives in code since v2.0
    ('webapp', 'url_prefix'),    # removed in v2.1 (X-Forwarded-Prefix)
}


def route(section: str, key: str) -> str:
    rule = ROUTING.get(section)
    if rule is None:
        return 'env'
    if isinstance(rule, str):
        return rule
    return rule.get(key, 'env')


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 2
    src = Path(sys.argv[1])
    if not src.exists():
        print(f'error: {src} not found')
        return 1

    out_site = src.parent / 'site.config'
    out_env = src.parent / 'environment.config'
    for out in (out_site, out_env):
        if out.exists():
            print(f'error: {out} already exists — refusing to overwrite')
            return 1

    cp = configparser.ConfigParser(inline_comment_prefixes=('#', ';'))
    cp.read(src)

    site = configparser.ConfigParser()
    env = configparser.ConfigParser()
    notices = []

    for section in cp.sections():
        if ROUTING.get(section) is None:
            notices.append(f'unknown section [{section}] routed to environment.config')
        for key, value in cp.items(section):
            if (section, key) in DROPPED_KEYS:
                notices.append(f'dropped [{section}] {key} (obsolete in v2.1)')
                continue
            target = site if route(section, key) == 'site' else env
            if not target.has_section(section):
                target.add_section(section)
            target.set(section, key, value)

    header = ('# Generated by tools/split_config.py from {}\n'
              '# Review, then restart the tracker. Keys equal to application\n'
              '# defaults may be deleted freely — unset keys fall back.\n\n')
    with open(out_site, 'w') as f:
        f.write(header.format(src.name))
        site.write(f)
    with open(out_env, 'w') as f:
        f.write(header.format(src.name))
        env.write(f)

    print(f'wrote {out_site}')
    print(f'wrote {out_env}')
    for n in notices:
        print(f'note: {n}')
    print(f'{src.name} left in place; v2.1 ignores it now that site.config exists.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
